; ==============================
;  Art Book Next - Theme Options
;  Formato compatible con ES-X
; ==============================


;--------------------------------
; Relación de aspecto (aspectRatio)
;--------------------------------
colorScheme = steam-deck
gameListStyle = metadata-on-miximage
soundSet = es-de
aspectRatio = 4-3
[aspectRatio]
type     = select
label    = Relación de aspecto - Aspect Ratio
apply_to = aspectRatio
values   = 16-9|16:9, 16-10|16:10, 4-3|4:3
default  = 16-9


;--------------------------------
; Estilo de la gamelist (gameListStyle)
;--------------------------------
[gameListStyle]
type     = select
label    = Estilo de lista - GameList Style
apply_to = gameListStyle
values   = metadata-on|Metadata ON, metadata-off|Metadata OFF, metadata-off-zoomed|Metadata OFF (Zoom), metadata-on-miximage|Metadata + Miximage
default  = metadata-on


;--------------------------------
; Esquema de colores (colorScheme)
;--------------------------------
[colorScheme]
type     = select
label    = Esquema de color - Color Scheme
apply_to = colorScheme
values   = art-book-next|Art Book Next, art-book|Art Book, snes|SNES, famicom|Famicom, steam-deck|Steam Deck, custom|Personalizado
default  = art-book-next


;--------------------------------
; Set de sonidos (soundSet)
;--------------------------------
[soundSet]
type     = select
label    = Sonidos del tema - Sound Set
apply_to = soundSet
values   = es-de|ES-DE, steam-os|Steam OS
default  = steam-os


;--------------------------------
; Perfiles extra (opcional)
; Igual que tus [layout_smd], [layout_psx]
; Podés más adelante crear:
;
; [colorScheme_snes]
; [colorScheme_famicom]
; etc.
;--------------------------------
